#!/bin/sh
#
# Usage: gvpn <host_or_dns_name>
# Description: Gets VPN IP for specific host / user

### Constants

ANSIBLE_DIR="$HOME/ansible/emsys/"
IP_REGEX="([0-9]{1,3}\.){3}[0-9]{1,3}"

ECHO_ERROR="\u274c"
ECHO_SUCCESS="\u2714"

### Functions

gvpn_host() {
  ip=$(cat $ANSIBLE_DIR/inventory | grep -i $1 | grep -i vpn_ip | grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}") >/dev/null

  # if [ -z $ip ]; then
    # vpnuser=$(cat host_vars/$1.workstations.ems/static_info | grep -i 'workstation_users:' -A1 | tail -n1 | awk '{$1=$1};1' | cut -d':' -f1)
    # ip=$(ansible officevpn -i inventory -u root -m shell -a "cat /var/log/openvpn-status.log" | grep -i $vpnuser | tail -n1 | cut -d',' -f1)
  # fi
  echo $ip
}

gvpn_log() {
  ip=$(ansible officevpn -i $ANSIBLE_DIR/inventory -u root -m shell -a "cat /var/log/openvpn-status.log" >/dev/null | grep -i $vpnuser | tail -n1 | cut -d',' -f1) >/dev/null

  echo $ip
}

usage() {
  echo "Usage: gvpn [[-u <user>] | [-m <hostname>] | [-h]]"
}

### Main

# vpn_user=
# host_name=

while [ "$1" != "" ]; do
  case $1 in
    -u | --user )
      shift
      vpn_user=$1
      ;;
    -m | --machine )
      shift
      host_name=$1
      ;;
    -h | --help )
      usage
      exit
      ;;
    * )
      usage
      exit 1
  esac
  shift
done

# Execute gvpn function
if [ -z $host_name ]; then
  ip=$(gvpn_host $host_name)
  if [ -z $ip ]; then
    # if [ -n $vpn_user ]; then
      # ip=$(gvpn_log $vpn_user)
      # echo "VPN IP for $vpn_user: $ip"
      # exit
    # fi

    echo "No VPN IP for $host_name!"
    exit 1
  fi

  echo "VPN IP for $host_name: $ip"
fi

if [ -z $vpn_ip ]; then
  ip=$(gvpn_log $vpn_user)
  if [ -z $ip ]; then
    echo "[ $($ECHO_ERROR) ] => No VPN IP for $host_name!"
    exit 1
  fi

  echo "[ $($ECHO_SUCCESS) ] => VPN IP for $vpn_user: $ip"
fi
