---
- name: "Customizing Ubuntu"
  hosts: all

  roles:
    - role: "apt"
      tags: apt

    - role: "gitui"
      tags: gitui

    - role: "polybar"
      tags: polybar

    - role: "common"
      tags: common

    - role: "vim"
      tags: vim

    - role: "omz"
      tags: omz

    - role: "terminal"
      tags: terminal

    - role: "virtualization"
      tags: vm
