---
- name: "Customizing Ubuntu"
  hosts: all

  roles:
    - role: "roles/apt"
      tags: apt

    - role: "roles/common"
      tags: common

    - role: "roles/vim"
      tags: vim

    - role: "roles/omz"
      tags: omz

    - role: "roles/terminal"
      tags: terminal
