---

- block:
  - name: "Update apt cache"
    ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: "Remove unwanted packages"
    ansible.builtin.apt:
      name: "{{ item }}"
      state: absent
    with_items: "{{ packages_absent }}"
    when: packages_absent is defined

  - name: "Installing packages"
    ansible.builtin.apt:
      name: "{{ item }}"
      state: latest
    with_items: "{{ packages_present }}"

  - name: "Upgrade all packages"
    ansible.builtin.apt: upgrade=yes force_apt_get=yes

  become: true

- name: "bat config"
  block:
  - name: "Fix bat installation ( 1 / 5 )"
    ansible.builtin.file:
      src: /usr/bin/batcat
      dest: /usr/local/bin/bat
      state: link

  - name: "Create bat config path ( 2 / 5 )"
    ansible.builtin.file:
      path: "{{ bat_path }}"
      state: directory
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: 0755

  - name: "Copy bat config ( 3 / 5 )"
    ansible.builtin.copy:
      src: files/bat.config
      dest: "{{ bat_path }}/config"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: 0664

  - name: "Create bat theme path ( 4 / 5 )"
    ansible.builtin.file:
      path: "{{ bat_path }}/themes"
      state: directory
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: 0755
    
  - name: "Download catppuccin theme ( 5 / 5 )"
    ansible.builtin.get_url:
      url: https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Macchiato.tmTheme
      dest: "{{ bat_path }}/themes/Catppuccin Macchiato.tmTheme"
      mode: 0644

