---
- name: "Update apt cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true

- name: "Installing packages"
  package:
    name:
      - jq
      - vim
      - zsh
      - python3-pip
      - locate
      - flameshot
      - exiftool
      - terminator
    state: latest
  become: true
