---
- name: "Clone github repos"
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - {"url": "https://github.com/supercrabtree/k.git", "dest": "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/k"}
    - {"url": "https://github.com/zsh-users/zsh-history-substring-search.git", "dest": "{{ ansible_env.HOME }}/.oh-my-zsh/plugins/zsh-history-substring-search"}
