---

- name: Install VirtualBox and Guest additions
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ vbox_packages }}"

- name: Set default VM folder
  ansible.builtin.shell:
    cmd: "vboxmanage setproperty machinefolder {{ vbox_iso_path }}"
  become_user: "{{ local_user }}"
